# https://docs.rs/i3status-rs/latest/i3status_rs/
icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:en_US) "
short = " $icon $timestamp.datetime(f:%R) "
[[block.click]]
button = "right"
cmd = "xdg-open https://calendar.google.com"
[[block.click]]
button = "left"
cmd = "gnome-clocks"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "custom"
command = "current-refresh-rate"
interval = 5
signal = 1 
[[block.click]]
button = "left"
cmd = "toggle-refresh-rate; pkill -RTMIN+1 i3status-rs"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol -t 3"

[[block]]
block = "sound"
device_kind = "source"
[[block.click]]
button = "left"
cmd = "pavucontrol -t 4"
